### ISSUE TITLE
Does not automatically install nanoleaf library

### ISSUE THREAD

**Issue by jassmith** [software-2/ha-aurora#2]
It was easy to install by hand, but yeah it doesn't install automatically.

**Comment by pancho-villa** [comment]
Edit the aurora.py file and move `from nanoleaf import Aurora` on line 1 to right above this line  `my_aurora = Aurora(host, apikey)` in the setup_platform function.

**Comment by elbogi** [comment]
Running Hassio inside Docker and need som help getting my Nanoleaf Aurora to function. Got the API (by using another linux computer). How should I import the correct files to get it working? 
Error in log:
`File "/config/custom_components/light/aurora.py", line 1, in <module>
    from nanoleaf import Aurora
ModuleNotFoundError: No module named 'nanoleaf'`

**Comment by StudioHawk** [comment]
Same problem as Elbogi

**Comment by jassmith** [comment]
I made a docker image of hass that has the nanoleaf library pre-installed to make life easier until this gets PR'd into hass itself.

https://hub.docker.com/r/jassmith/home-assistant-nanoleaf/

All it does is install nanoleaf. You still install aurora.py in the custom_components directory as I didn't want to fork hass itself.

Save you 5 minutes of work or so :)

**Comment by SimplyMinimal** [comment]
Depending on how your home assistant is [installed ](https://home-assistant.io/docs/installation/) you just need to do the following (i.e. after becoming homeassistant):

`pip install nanoleaf`

**Comment by VdkaShaker** [comment]
I'm running Hass.io and don't know if I can install new or different docker images on top of that (or how to even do it).  Is this coming to standard components soon?

**Comment by elbogi** [comment]
Ok, so this is what I did after setting up my new hass.io on my Raspberry3:
- Installed hass.io as [instructed](https://home-assistant.io/getting-started/).
- Enable ssh og samba to get access to "config" folder
- From [this site](https://github.com/software-2/ha-aurora), do as instructed but copy the file _aurora.py_ to _/config/custom_components/light_.
- Then the "fun" part begins. Do as instructed on [how to gain access to the host](https://home-assistant.io/developers/hassio/debugging/).
- After logging in with _ssh root@hassio.local -p 22222_, find the name of your docker container. Usually this is called _homeassistant_ when hass.io is installed. You can verify by running `docker ps`.
- Run the following command: `docker exec -it homeassistant bash`- (homeassistant is what is default for hass.io)
- Then enter `pip3 install nanoleaf --upgrade`. It should install the nanoleaf components.
- If you havne't already got it, you can follow the instructions [here](https://github.com/software-2/nanoleaf) to get your Aurora IP and API. (I had to run these commands in `python3` instead of python). After getting this information you should be all set.
- Type `exit` to exit the container and then exit this SSH session.
- Log into your hass.io and restart homeassistant (hassio ha restart) and check your logs. This approach worked for me and my Aurora is once more working in the hass.io environment.

I hope this "how-to" is of some help.

**Comment by VdkaShaker** [comment]
@elbogi can’t wait to try out your instructions. Really appreciate the detail.

**Comment by VdkaShaker** [comment]
@elbogi I'm stuck again.  I'm trying to run the commands to get my API key and its just not working.

On my Mac I'm opening a Terminal window and running Python3.  Press the button my my Aurora until the indicator light begins to blink.  From the prompt I type the first command:  `from nanoleaf import setup` and I get 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nanoleaf'
```

The second command fails because the first did of course.  

What am I not doing right?  Thanks for any help.

**Comment by elbogi** [comment]
Sorry for the late response, been busy at work. When you've attached to the docker (ocker exec -it homeassistant bash) you were able to install nanoleaf, correct? If and when this component is installed (with pip3 install nanoleaf --upgrade) then type "python3" at the prompt. Do not exit the docker. After typing "python3" the prefix changes to something like >>>. Then you follow the instructions [here](https://github.com/software-2/nanoleaf) for **Finding IP address** and then **Generate auth token**. then type "exit()" to exit python. Then exit docker, then exit ssh session.

**Comment by VdkaShaker** [comment]
@elbogi  I went back to the docker as you mentioned and entered the Python environment.  I already have the IP address so I ran the commands and got my API key.  Thanks again for the pointers.

[edit] unfortunately something is still missing.  All the components installed when ran through the steps the other day, and now I have an API key, but here's my log:

```
2018-01-30 21:37:21 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.light.aurora. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/light/aurora.py", line 1, in <module>
    from nanoleaf import Aurora
ModuleNotFoundError: No module named 'nanoleaf'
2018-01-30 21:37:21 ERROR (MainThread) [homeassistant.loader] Unable to find component light.aurora
```

I'll have to keep digging.

**Comment by elbogi** [comment]
Did you copy the aurora.py file as described [here](https://github.com/software-2/ha-aurora)? Copy `aurora.py` into `/config/custom_components/light`

**Comment by VdkaShaker** [comment]
> Did you copy the aurora.py file as described

Yes, but no luck.  I waited until I updated HA again and re-did the PIP script to reinstall the components, and its working now.  Maybe I had done a point release and forgot I had to reinstall these?  Anyway.  Thanks again for your help!
