### ISSUE TITLE
Broken In HA 0.56.2

### ISSUE THREAD

**Issue by fia5000** [software-2/ha-aurora#6]
Appears something changed in the recent HASS versions that broke this.
```

2017-10-24 10:55:56 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform aurora Traceback (most recent call last): File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 170, in _async_setup_platform SLOW_SETUP_MAX_WAIT, loop=self.hass.loop) File "/usr/lib/python3.4/asyncio/tasks.py", line 372, in wait_for return fut.result() File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result raise self._exception File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run result = self.fn(*self.args, **self.kwargs) File "/home/homeassistant/.homeassistant/custom_components/light/aurora.py", line 38, in setup_platform add_devices([AuroraLight(my_aurora)]) File "/home/homeassistant/.homeassistant/custom_components/light/aurora.py", line 66, in __init__ self._brightness = brightness_scale_nanoleaf_to_hass(light.brightness) File "/home/homeassistant/.homeassistant/custom_components/light/aurora.py", line 46, in brightness_scale_nanoleaf_to_hass return range_value * 2.55 TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

```

**Comment by fia5000** [comment]
Closing. Checked out the latest module from your upstream repo. Seems to have fixed the crash.
